### ISSUE TITLE
How to specify multiple categories?

### ISSUE THREAD

**Issue by victorhooi** [verybada/rarbgapi#14]
Is it possible to specify multiple categories? (e.g. CATEGORY_TV_EPISODES, CATEGORY_TV_EPISODES_HD and CATEGORY_TV_EPISODES_UHD).

It's not clear from the rarbgapi documentation how to do this?

**Comment by AndydeCleyre** [comment]
Trying to use the new `categories` as in the README:

```
Traceback (most recent call last):
  File "/home/andy/.local/share/venvs/e891f56131f0d3a272975f93ead1f3c7/venv/lib/python3.8/site-packages/rarbgapi/rarbgapi.py", line 163, in wrapper
    resp = func(self, *args, **kwargs)
  File "/home/andy/.local/share/venvs/e891f56131f0d3a272975f93ead1f3c7/venv/lib/python3.8/site-packages/rarbgapi/rarbgapi.py", line 298, in search
    return self._query('search', **self.backward_compability(kwargs))
  File "/home/andy/.local/share/venvs/e891f56131f0d3a272975f93ead1f3c7/venv/lib/python3.8/site-packages/rarbgapi/rarbgapi.py", line 109, in _query
    params['category'] = ';'.join(kwargs['categories'])
TypeError: sequence item 0: expected str instance, int found
```

**Comment by verybada** [comment]
@AndydeCleyre 
Please try 0.4.1

**Comment by AndydeCleyre** [comment]
Yes, works with `0.4.1`, thanks!
